project:
  type: website
  output-dir: docs
website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Projects"
        menu:
          - stat515.qmd
      

format:
  html:
    theme: portfolio
    mainfont: arial
    fontsize: 1.5rem
    css: styles.css
    toc: true



